#!/usr/bin/python3

srcs = [
  'bytes',
  'camera',
  'camera_control',
  'gl_util',
  'gl_viewport_control',
  'glfw_window',
  'image',
  'image_hdr',
  'image_png',
  'main',
  'math3d',
  'mesh',
  'object',
  'ohno',
  'util'
]

build = open('build.ninja', 'w')

build.write('''cc = clang++
cflags = -std=c++11 -Wall -Wextra -Wno-unused-parameter -g -O0
libs = -lm -lGL -lGLEW -lglfw -lpng

rule cc
  depfile = $out.d
  command = $cc -c $cflags -MMD -MF $out.d -o $out $in

rule ln
  command = $cc $libs -o $out $in

build out/a.out: ln %s

%s
''' % (' '.join(['out/' + s + '.o' for s in srcs]),
       '\n'.join(['build out/' + s + '.o: cc src/' + s + '.cc' for s in srcs]))
)

build.close()
